dist: trusty
sudo: required
language: ruby
services:
- postgresql
rvm:
# The latest ruby that is pre-installed on Travis Trusty
- 2.4.1
env:
  global:
  - TRAVIS=1 CI=1 COVERAGE=1
before_install:
- psql -c 'create database forum_test;' -U postgres
- "gem update --system --no-document --quiet"
- "gem install bundler --no-document"
- "gem install rubocop --no-document"
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug

# Avoid rake here, as the RSpec test task spawns a new process which does not run via bundler.
script: "bundle exec rspec --format d && bundle exec rubocop"